apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ .ServiceName }}
    commit: "{{ .Commit }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: {{ .ServiceName }}-https
spec:
  rules:
  - host: {{ .ServiceName }}.{{ .UrlDomain }}
    http:
      paths:
      - backend:
          serviceName: {{ .ServiceName }}
          servicePort: 443
  tls:
  - hosts:
    - {{ .ServiceName }}.{{ .UrlDomain }}
    secretName: tls-{{ .ServiceName }}.{{ .UrlDomain }}
