apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .ServiceName }}
    commit: "{{ .Commit }}"
  name: {{ .ServiceName }}
spec:
  ports:
  - name: task
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ .ServiceName }}
  type: ClusterIP
